import React from 'react';
import Head from "next/head";
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import { Card } from 'react-bootstrap';


export default function Home() {
  return (
    <div className={styles.container}>
      
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue sur notre beau site internet !
        </h1>

        <p className={styles.description}>
          Venez dépensez vos thunasses par ici svp.
        </p>
      </main>

      <footer className={styles.footer}>
        Footer déja fait less go
      </footer>
    </div>
  )
}