import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../css/Home.module.css'
import MyNavbar from '../components/Navigation'
import Footer from '../components/Footer'

 function Home() {
  return (
    <div>
      <Head>
        <title>WebSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavbar />
      <main>
        <h1>Hello World !</h1>
      </main>

      
          <Footer/>
      
    </div>
  )
}
export default Home;